### ISSUE TITLE
TOMCAT_LOCATION uses the wrong path

### ISSUE THREAD

**Issue by m1no** [atende/crowd#1]
When not setting an env var for TOMCAT_LOCATION the scala script fails. Because it tries to access /opt/crowd/conf/ where it should access /opt/crowd/apache-tomcat/conf.

The default is broken when not setting it, and the manual workaround is TOMCAT_LOCATION=/opt/crowd/apache-tomcat/

**Comment by giovannicandido** [comment]
Hi @m1no. Thanks for the report.
This is the expected behaviour because the script https://github.com/atende/crowd/blob/master/scripts/run_impl.sh overrides the TOMCAT_LOCATION and is read by the run.sh. It should be a problem if the TOMCAT_LOCATION is not overrided correctly by the script. 
And it was designed this way because I use the same set of scripts to install Jira, Confluence, Stash, Crowd and Bamboo with the same features like proxy configuration, and secondary port configuration.
What should I do to reproduce the problem? I was a problem with the recent builds because the stash 3.8.0 change the location for the server.xml file, could you try update the image with docker pull atende/stash and see if works?
